apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-ci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app-ci
  template:
    metadata:
      labels:
        app: register-app-ci
    spec:
      containers:
        - name: register-app-ci
          image: benghalemaziz/register-app-ci:1.0.0-10
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
